TARGET_TYPE := so
TARGET := libmp4.so

LOCAL_INC 	+= -I./include

LOCAL_SRC +=                  \
	src/avc1_box.c      \
	src/avcc_box.c      \
	src/box.c           \
	src/ctts_box.c      \
	src/dinf_box.c      \
	src/dref_box.c      \
	src/esds_box.c      \
	src/free_box.c      \
	src/ftyp_box.c      \
	src/hdlr_box.c      \
	src/hmhd_box.c      \
	src/mdat_box.c      \
	src/mdhd_box.c      \
	src/mdia_box.c      \
	src/minf_box.c      \
	src/moov_box.c      \
	src/mp4a_box.c      \
	src/mp4_bits.c      \
	src/mp4.c           \
	src/mvhd_box.c      \
	src/nmhd_box.c      \
	src/smhd_box.c      \
	src/sowt_box.c      \
	src/stbl_box.c      \
	src/stco_box.c      \
	src/stsc_box.c      \
	src/stsd_box.c      \
	src/stss_box.c      \
	src/stsz_box.c      \
	src/stts_box.c      \
	src/tkhd_box.c      \
	src/trak_box.c      \
	src/url_box.c      \
	src/vmhd_box.c      \
	src/h264.c

include $(TOPDIR)/rule.mk
