#!/bin/bash
CC=arm-hisiv300-linux-gcc

# Fix the language to get consistent output
LC_ALL=C
export LC_ALL

TIMESTAMP=`date`
APP_COMPILE_BY=$(whoami | sed 's/\\/\\\\/')
APP_COMPILE_HOST=`hostname`

UTS_VERSION="$TIMESTAMP"

# Truncate to maximum length

UTS_LEN=64
UTS_TRUNCATE="cut -b -$UTS_LEN"

# Generate a temporary compile.h

( echo /\* This file is auto generated \*/

  echo \#ifndef __COMPILE_H__
  echo \#define __COMPILE_H__
  echo

  echo \#define UTS_VERSION \"`echo $UTS_VERSION | $UTS_TRUNCATE`\"

  echo \#define APP_COMPILE_BY \"`echo $APP_COMPILE_BY | $UTS_TRUNCATE`\"
  echo \#define APP_COMPILE_HOST \"`echo $APP_COMPILE_HOST | $UTS_TRUNCATE`\"

  echo \#define APP_COMPILER \"`$CC -v 2>&1 | tail -n 1`\"

  echo
  echo \#endif /*__COMPILE_H__*/
) > compile.h
